; Script generated by the Inno Script Studio Wizard.
; SEE THE DOCUMENTATION FOR DETAILS ON CREATING INNO SETUP SCRIPT FILES!

#define MyAppName "Yadd To Map"
#define MyAppVersion "1.1"
#define MyAppPublisher "F5065SWL"
#define MyAppExeName "yadd2map.exe"
#define CreationDate GetDateTimeString('ddmmyy', '-', ':');

[Setup]
; NOTE: The value of AppId uniquely identifies this application.
; Do not use the same AppId value in installers for other applications.
; (To generate a new GUID, click Tools | Generate GUID inside the IDE.)
AppId={{A8AC4B0F-B99E-4DC0-A6FC-08A4196DD21F}
AppName={#MyAppName}
AppVersion={#MyAppVersion}
;AppVerName={#MyAppName} {#MyAppVersion}
AppPublisher={#MyAppPublisher}
DefaultDirName={userdocs}\Yadd2Map
DefaultGroupName={#MyAppName}
LicenseFile=..\COPYING
OutputBaseFilename=setup_Yadd2Map_{#CreationDate}
Compression=lzma
SolidCompression=yes

[Languages]
Name: "english"; MessagesFile: "compiler:Default.isl"
Name: "french"; MessagesFile: "compiler:Languages\French.isl"

[Tasks]
Name: "desktopicon"; Description: "{cm:CreateDesktopIcon}"; GroupDescription: "{cm:AdditionalIcons}"; Flags: unchecked

[Files]
Source: "..\yadd2map.exe"; DestDir: "{pf}\yadd2map"; Flags: ignoreversion
Source: "..\db\logbook.db"; DestDir: "{pf}\yadd2map\db"; Flags: ignoreversion onlyifdoesntexist uninsneveruninstall; Permissions: authusers-full
Source: "..\manual\doc_fr.pdf"; DestDir: "{pf}\yadd2map\manual"; Flags: ignoreversion
Source: "..\..\sqlite3.dll"; DestDir: "{pf}\yadd2map"
Source: "..\COPYING"; DestDir: "{pf}\yadd2map"; Flags: ignoreversion
Source: "..\CREDITS"; DestDir: "{pf}\yadd2map"; Flags: ignoreversion
Source: "..\map\favicon.png"; DestDir: "{pf}\yadd2map\map"
Source: "..\mime.types"; DestDir: "{pf}\yadd2map"
Source: "..\map\404.html"; DestDir: "{pf}\yadd2map\map"; Flags: ignoreversion
Source: "..\map\500.html"; DestDir: "{pf}\yadd2map\map"; Flags: ignoreversion
Source: "..\map\favicon.png"; DestDir: "{pf}\yadd2map\map"; Flags: ignoreversion
Source: "..\map\index.html"; DestDir: "{pf}\yadd2map\map"; Flags: ignoreversion
Source: "..\map\map.html"; DestDir: "{pf}\yadd2map\map"; Flags: ignoreversion
Source: "..\map\yadd2map.css"; DestDir: "{pf}\yadd2map\map"; Flags: ignoreversion
Source: "..\map\img\favicon.png"; DestDir: "{pf}\yadd2map\map\img"; Flags: ignoreversion
Source: "..\map\js\distance.js"; DestDir: "{pf}\yadd2map\map\js"; Flags: ignoreversion
Source: "..\map\js\leaflet.label.css"; DestDir: "{pf}\yadd2map\map\js"; Flags: ignoreversion
Source: "..\map\js\leaflet.label.js"; DestDir: "{pf}\yadd2map\map\js"; Flags: ignoreversion
Source: "..\map\js\yadd2map.js"; DestDir: "{pf}\yadd2map\map\js"; Flags: ignoreversion
Source: "..\map\lib\distance.js"; DestDir: "{pf}\yadd2map\map\lib"; Flags: ignoreversion
Source: "..\map\data\home.json"; DestDir: "{pf}\yadd2map\map\data"; Permissions: authusers-full

[Icons]
Name: "{group}\{#MyAppName}"; Filename: "{pf}\yadd2map\yadd2map.exe"
Name: "{commondesktop}\{#MyAppName}"; Filename: "{pf}\yadd2map\yadd2map.exe"; Tasks: desktopicon
Name: "{group}\Documentation"; Filename: "{pf}\yadd2map\manual\doc_fr.pdf"

[Run]
Filename: "{pf}\yadd2map\{#MyAppExeName}"; Description: "{cm:LaunchProgram,{#StringChange(MyAppName, '&', '&&')}}"; Flags: nowait postinstall skipifsilent

[Dirs]
Name: "{pf}\yadd2map\logs"; Permissions: authusers-full
Name: "{pf}\yadd2map\map\data"; Permissions: authusers-full
Name: "{pf}\yadd2map\db"; Permissions: authusers-full
Name: "{app}\map\data\"
Name: "{app}\map\img\"
Name: "{app}\map\js\"
Name: "{app}\map\lib\"
Name: "{app}\map\lib\Leaflet.label\"
