; Script generated by the Inno Script Studio Wizard.
; SEE THE DOCUMENTATION FOR DETAILS ON CREATING INNO SETUP SCRIPT FILES!

#define MyAppName "Yadd To Map"
#define MyAppVersion "1.0"
#define MyAppPublisher "F5065SWL"
#define MyAppExeName "yadd2map.exe"

[Setup]
; NOTE: The value of AppId uniquely identifies this application.
; Do not use the same AppId value in installers for other applications.
; (To generate a new GUID, click Tools | Generate GUID inside the IDE.)
AppId={{A8AC4B0F-B99E-4DC0-A6FC-08A4196DD21F}
AppName={#MyAppName}
AppVersion={#MyAppVersion}
;AppVerName={#MyAppName} {#MyAppVersion}
AppPublisher={#MyAppPublisher}
DefaultDirName={userdocs}\Yadd2Map
DefaultGroupName={#MyAppName}
LicenseFile=..\COPYING
OutputBaseFilename=setup_Yadd2Map
Compression=lzma
SolidCompression=yes

[Languages]
Name: "english"; MessagesFile: "compiler:Default.isl"
Name: "french"; MessagesFile: "compiler:Languages\French.isl"

[Tasks]
Name: "desktopicon"; Description: "{cm:CreateDesktopIcon}"; GroupDescription: "{cm:AdditionalIcons}"; Flags: unchecked

[Files]
Source: "..\yadd2map.exe"; DestDir: "{userdocs}\yadd2map"; Flags: ignoreversion
Source: "..\db\logbook.db"; DestDir: "{userdocs}\yadd2map"; Flags: ignoreversion onlyifdoesntexist uninsneveruninstall
Source: "..\map\lib\*"; DestDir: "{userdocs}\yadd2map\map\lib"; Flags: ignoreversion recursesubdirs createallsubdirs
Source: "..\manual\doc_fr.pdf"; DestDir: "{userdocs}\yadd2map\manual"; Flags: ignoreversion
Source: "..\lib\32\sqlite3.dll"; DestDir: "{userdocs}\yadd2map"
Source: "..\map\map.html"; DestDir: "{userdocs}\yadd2map\map"; Flags: ignoreversion
Source: "..\COPYING"; DestDir: "{userdocs}\yadd2map"; Flags: ignoreversion
Source: "..\CREDITS"; DestDir: "{userdocs}\yadd2map"; Flags: ignoreversion
Source: "..\map\favicon.png"; DestDir: "{userdocs}\yadd2map\map"

[Icons]
Name: "{group}\{#MyAppName}"; Filename: "{userdocs}\yadd2map\{#MyAppExeName}"
Name: "{commondesktop}\{#MyAppName}"; Filename: "{userdocs}\yadd2map\{#MyAppExeName}"; Tasks: desktopicon
Name: "{group}\Documentation"; Filename: "{userdocs}\yadd2map\manual\doc_fr.pdf"

[Run]
Filename: "{userdocs}\yadd2map\{#MyAppExeName}"; Description: "{cm:LaunchProgram,{#StringChange(MyAppName, '&', '&&')}}"; Flags: nowait postinstall skipifsilent

[Dirs]
Name: "{userdocs}\yadd2map\logs"
Name: "{userdocs}\yadd2map\map\data"
